<Project Sdk="Microsoft.NET.Sdk.Web">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
		<PackageReference Include="Serilog.AspNetCore" Version="10.0.0" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" Version="10.0.3" />
		<PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="10.0.3" />
		<PackageReference Include="Hangfire.Core" Version="1.8.17" />
		<PackageReference Include="Hangfire.SqlServer" Version="1.8.17" />
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.17" />
		<PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="10.0.3" />
		<PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="10.0.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="../Modules/TabelasGerais/Parameters/Parameters.Presentation/Parameters.Presentation.csproj" />
		<ProjectReference Include="../Modules/Gestao/Providers/Providers.Presentation/Providers.Presentation.csproj" />
		<ProjectReference Include="../Modules/Gestao/Clients/Clients.Presentation/Clients.Presentation.csproj" />
		<ProjectReference Include="../Modules/Gestao/Stocks/Stocks.Presentation/Stocks.Presentation.csproj" />
		<ProjectReference Include="../Modules/Gestao/Dossiers/Dossiers.Presentation/Dossiers.Presentation.csproj" />
		<ProjectReference Include="../Modules/Gestao/Invoices/Invoices.Presentation/Invoices.Presentation.csproj" />
		<ProjectReference Include="../Modules/Gestao/Receipts/Receipts.Presentation/Receipts.Presentation.csproj" />
		<ProjectReference Include="../Modules/Gestao/Advances/Advances.Presentation/Advances.Presentation.csproj" />
		<ProjectReference Include="../Modules/Gestao/Treasury/Treasury.Presentation/Treasury.Presentation.csproj" />
		<ProjectReference Include="../Modules/Ai/Agent.Presentation/Agent.Presentation.csproj" />
		<ProjectReference Include="../Modules/TabelasGerais/Currencies/Currencies.Presentation/Currencies.Presentation.csproj" />
		<ProjectReference Include="../Modules/TabelasGerais/VatTaxes/VatTaxes.Presentation/VatTaxes.Presentation.csproj" />
		<ProjectReference Include="../Modules/Audit/Audit.Presentation/Audit.Presentation.csproj" />
		<ProjectReference Include="../Modules/Auth/Auth.Presentation/Auth.Presentation.csproj" />
		<ProjectReference Include="../Modules/Auth/Auth.Infrastructure/Auth.Infrastructure.csproj" />
		<ProjectReference Include="../Admin.UI/Admin.UI.csproj" />
		<ProjectReference Include="../Shared/Shared.Infrastructure/Shared.Infrastructure.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Folder Include="logs\" />
		<Folder Include="Services\" />
	</ItemGroup>

</Project>

